---
- name: Configure unattended-upgrades
  ansible.builtin.copy:
    src: apt-20auto-upgrades
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    mode: '0644'

- name: Configure unattended-upgrades behavior
  ansible.builtin.copy:
    src: apt-50unattended-upgrades
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    mode: '0644'

