# Ansible Collection Requirements
# Install with: task ansible:install

collections:
  - name: https://github.com/ansible-collections/ansible.posix
    type: git
    version: "2.1.0"
  - name: https://github.com/ansible-collections/community.docker
    type: git
    version: "5.0.5"
